using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CreateSheetsFromVideo
{
    public enum Pitch
    {
        C,
        Cis,
        D,
        Es,
        E,
        F,
        Fis,
        G,
        Gis,
        A,
        Bes,
        B,
        C1,
        Cis1,
        D1,
        Es1,
        E1,
        F1,
        Fis1,
        G1,
        Gis1,
        A1,
        Bes1,
        B1,
        C2,
        Cis2,
        D2,
        Es2,
        E2,
        F2,
        Fis2,
        G2,
        Gis2,
        A2,
        Bes2,
        B2,
        C3,
        Cis3,
        D3,
        Es3,
        E3,
        F3,
        Fis3,
        G3,
        Gis3,
        A3,
        Bes3,
        B3,
        C4,
        Cis4,
        D4,
        Es4,
        E4,
        F4,
        Fis4,
        G4,
        Gis4,
        A4,
        Bes4,
        B4,
        C5,
        Cis5,
        D5,
        Es5,
        E5,
        F5,
        Fis5,
        G5,
        Gis5,
        A5,
        Bes5,
        B5,
        C6,
        Cis6,
        D6,
        Es6,
        E6,
        F6,
        Fis6,
        G6,
        Gis6,
        A6,
        Bes6,
        B6,
    }

    public enum WhitePitch
    {
        C = Pitch.C,
        D = Pitch.D,
        E = Pitch.E,
        F = Pitch.F,
        G = Pitch.G,
        A = Pitch.A,
        B = Pitch.B,
        C1 = Pitch.C1,
        D1 = Pitch.D1,
        E1 = Pitch.E1,
        F1 = Pitch.F1,
        G1 = Pitch.G1,
        A1 = Pitch.A1,
        B1 = Pitch.B1,
        C2 = Pitch.C2,
        D2 = Pitch.D2,
        E2 = Pitch.E2,
        F2 = Pitch.F2,
        G2 = Pitch.G2,
        A2 = Pitch.A2,
        B2 = Pitch.B2,
        C3 = Pitch.C3,
        D3 = Pitch.D3,
        E3 = Pitch.E3,
        F3 = Pitch.F3,
        G3 = Pitch.G3,
        A3 = Pitch.A3,
        B3 = Pitch.B3,
        C4 = Pitch.C4,
        D4 = Pitch.D4,
        E4 = Pitch.E4,
        F4 = Pitch.F4,
        G4 = Pitch.G4,
        A4 = Pitch.A4,
        B4 = Pitch.B4,
        C5 = Pitch.C5,
        D5 = Pitch.D5,
        E5 = Pitch.E5,
        F5 = Pitch.F5,
        G5 = Pitch.G5,
        A5 = Pitch.A5,
        B5 = Pitch.B5,
        C6 = Pitch.C6,
        D6 = Pitch.D6,
        E6 = Pitch.E6,
        F6 = Pitch.F6,
        G6 = Pitch.G6,
        A6 = Pitch.A6,
        B6 = Pitch.B6,
    }

    public enum BlackPitch
    {
        Cis = Pitch.Cis,
        Es = Pitch.Es,
        Fis = Pitch.Fis,
        Gis = Pitch.Gis,
        Bes = Pitch.Bes,
        Cis1 = Pitch.Cis1,
        Es1 = Pitch.Es1,
        Fis1 = Pitch.Fis1,
        Gis1 = Pitch.Gis1,
        Bes1 = Pitch.Bes1,
        Cis2 = Pitch.Cis2,
        Es2 = Pitch.Es2,
        Fis2 = Pitch.Fis2,
        Gis2 = Pitch.Gis2,
        Bes2 = Pitch.Bes2,
        Cis3 = Pitch.Cis3,
        Es3 = Pitch.Es3,
        Fis3 = Pitch.Fis3,
        Gis3 = Pitch.Gis3,
        Bes3 = Pitch.Bes3,
        Cis4 = Pitch.Cis4,
        Es4 = Pitch.Es4,
        Fis4 = Pitch.Fis4,
        Gis4 = Pitch.Gis4,
        Bes4 = Pitch.Bes4,
        Cis5 = Pitch.Cis5,
        Es5 = Pitch.Es5,
        Fis5 = Pitch.Fis5,
        Gis5 = Pitch.Gis5,
        Bes5 = Pitch.Bes5,
        Cis6 = Pitch.Cis6,
        Es6 = Pitch.Es6,
        Fis6 = Pitch.Fis6,
        Gis6 = Pitch.Gis6,
        Bes6 = Pitch.Bes6,
    }
}
